encoder-embed-dim-subtransformer: 512
decoder-embed-dim-subtransformer: 768

encoder-ffn-embed-dim-all-subtransformer: [3072, 2048, 3072, 1024, 4096, 3072]
decoder-ffn-embed-dim-all-subtransformer: [3072, 3072, 3072]

encoder-layer-num-subtransformer: 6
decoder-layer-num-subtransformer: 3

encoder-self-attention-heads-all-subtransformer: [8, 4, 4, 4, 4, 16]
decoder-self-attention-heads-all-subtransformer: [16, 16, 4]
decoder-ende-attention-heads-all-subtransformer: [16, 16, 4]

decoder-arbitrary-ende-attn-all-subtransformer: [1, 1, 1]

encoder-block-types-all-subtransformer: [self_attention+lightweight_conv, self_attention+lightweight_conv, self_attention+lightweight_conv, self_attention+lightweight_shiftadd, self_attention+lightweight_shiftadd, self_attention]
decoder-block-types-all-subtransformer: [self_attention+lightweight_conv, self_attention, self_attention, self_attention+lightweight_shiftadd, self_attention+lightweight_shiftadd, self_attention+lightweight_conv]
