encoder-embed-dim-subtransformer: 640
decoder-embed-dim-subtransformer: 512

encoder-ffn-embed-dim-all-subtransformer: [1024, 3072, 1024, 2048, 2048, 2048]
decoder-ffn-embed-dim-all-subtransformer: [3072, 3072, 3072]

encoder-layer-num-subtransformer: 6
decoder-layer-num-subtransformer: 3

encoder-self-attention-heads-all-subtransformer: [4, 8, 4, 4, 8, 4]
decoder-self-attention-heads-all-subtransformer: [4, 4, 8]
decoder-ende-attention-heads-all-subtransformer: [8, 8, 4]

decoder-arbitrary-ende-attn-all-subtransformer: [2, -1, -1]

encoder-block-types-all-subtransformer: [self_attention, self_attention, self_attention, self_attention, self_attention, self_attention]
decoder-block-types-all-subtransformer: [self_attention, self_attention, self_attention, self_attention, self_attention, self_attention]
