encoder-embed-dim-subtransformer: 512
decoder-embed-dim-subtransformer: 512

encoder-ffn-embed-dim-all-subtransformer: [2048, 3072, 3072, 2048, 1024, 1024]
decoder-ffn-embed-dim-all-subtransformer: [3072, 3072, 3072]

encoder-layer-num-subtransformer: 6
decoder-layer-num-subtransformer: 3

encoder-self-attention-heads-all-subtransformer: [8, 4, 8, 4, 4, 4]
decoder-self-attention-heads-all-subtransformer: [8, 8, 8]
decoder-ende-attention-heads-all-subtransformer: [4, 8, 8]

decoder-arbitrary-ende-attn-all-subtransformer: [2, 1, -1]

encoder-block-types-all-subtransformer: [self_attention, self_attention, self_attention, self_attention, self_attention, self_attention]
decoder-block-types-all-subtransformer: [self_attention, self_attention, self_attention, self_attention, self_attention, self_attention]

# | Iteration 29, Lowest loss: 7.448144172779036
# | Config for lowest loss model: {'encoder': {'encoder_embed_dim': 512, 'encoder_layer_num': 6, 'encoder_ffn_embed_dim': [2048, 3072, 3072, 2048, 1024, 1024], 'encoder_self_attention_heads': [8, 4, 8, 4, 4, 4], 'encoder_block_types': ['lightweight_add', 'self_attention', 'lightweight_add', 'self_attention+lightweight_conv', 'self_attention+lightweight_shiftadd', 'lightweight_add']}, 'decoder': {'decoder_embed_dim': 512, 'decoder_layer_num': 3, 'decoder_ffn_embed_dim': [3072, 3072, 3072, 2048, 1024, 3072], 'decoder_self_attention_heads': [8, 8, 8, 4, 8, 8], 'decoder_ende_attention_heads': [4, 8, 8, 4, 4, 8], 'decoder_arbitrary_ende_attn': [2, 1, -1, -1, -1, -1], 'decoder_block_types': ['self_attention+lightweight_conv', 'self_attention+lightweight_conv', 'self_attention+lightweight_conv', 'self_attention+lightweight_conv', 'self_attention+lightweight_add', 'self_attention']}}
# | Predicted latency for lowest loss model: 133.43260288238525
