encoder-embed-dim-subtransformer: 512
decoder-embed-dim-subtransformer: 512

encoder-ffn-embed-dim-all-subtransformer: [2048, 4096, 4096, 1024, 4096, 4096]
decoder-ffn-embed-dim-all-subtransformer: [4096, 4096, 4096]

encoder-layer-num-subtransformer: 6
decoder-layer-num-subtransformer: 3

encoder-self-attention-heads-all-subtransformer: [8, 16, 4, 4, 4, 4]
decoder-self-attention-heads-all-subtransformer: [8, 16, 8]
decoder-ende-attention-heads-all-subtransformer: [4, 4, 16]

decoder-arbitrary-ende-attn-all-subtransformer: [2, -1, -1]

encoder-block-types-all-subtransformer: [lightweight_add, self_attention+lightweight_add, lightweight_add, lightweight_add, self_attention, lightweight_add]
decoder-block-types-all-subtransformer: [self_attention+lightweight_conv, self_attention, self_attention, self_attention+lightweight_shiftadd, self_attention, self_attention+lightweight_shiftadd]
