encoder-embed-dim-subtransformer: 512
decoder-embed-dim-subtransformer: 768

encoder-ffn-embed-dim-all-subtransformer: [2048, 4096, 3072, 4096, 4096, 4096]
decoder-ffn-embed-dim-all-subtransformer: [4096, 4096, 4096, 4096, 4096]

encoder-layer-num-subtransformer: 6
decoder-layer-num-subtransformer: 5

encoder-self-attention-heads-all-subtransformer: [16, 4, 16, 4, 16, 8]
decoder-self-attention-heads-all-subtransformer: [16, 16, 4, 8, 16]
decoder-ende-attention-heads-all-subtransformer: [16, 8, 8, 4, 16]

decoder-arbitrary-ende-attn-all-subtransformer: [1, 2, 2, 2, 1]

encoder-block-types-all-subtransformer: [self_attention+lightweight_conv, self_attention+lightweight_shiftadd, self_attention+lightweight_add, self_attention+lightweight_conv, self_attention+lightweight_add, self_attention+lightweight_shiftadd]
decoder-block-types-all-subtransformer: [self_attention+lightweight_shiftadd, self_attention+lightweight_conv, self_attention+lightweight_shiftadd, self_attention+lightweight_add, self_attention+lightweight_shiftadd, self_attention+lightweight_shiftadd]
