encoder-embed-dim-subtransformer: 512
decoder-embed-dim-subtransformer: 512

encoder-ffn-embed-dim-all-subtransformer: [2048, 1024, 1024, 1024, 2048, 4096]
decoder-ffn-embed-dim-all-subtransformer: [4096, 3072, 3072]

encoder-layer-num-subtransformer: 6
decoder-layer-num-subtransformer: 3

encoder-self-attention-heads-all-subtransformer: [4, 8, 8, 4, 4, 8]
decoder-self-attention-heads-all-subtransformer: [4, 16, 8]
decoder-ende-attention-heads-all-subtransformer: [4, 16, 16]

decoder-arbitrary-ende-attn-all-subtransformer: [2, 2, -1]

encoder-block-types-all-subtransformer: [self_attention+lightweight_conv, self_attention+lightweight_conv, self_attention, self_attention+lightweight_add, self_attention, self_attention]
decoder-block-types-all-subtransformer: [self_attention+lightweight_conv, self_attention, self_attention, self_attention+lightweight_shiftadd, self_attention+lightweight_shiftadd, self_attention]
