encoder-embed-dim-subtransformer: 512
decoder-embed-dim-subtransformer: 512

encoder-ffn-embed-dim-all-subtransformer: [2048, 2048, 2048, 2048, 2048, 2048]
decoder-ffn-embed-dim-all-subtransformer: [2048, 2048, 2048, 2048, 2048, 2048]

encoder-layer-num-subtransformer: 6
decoder-layer-num-subtransformer: 6

encoder-self-attention-heads-all-subtransformer: [8, 8, 8, 8, 8, 8]
decoder-self-attention-heads-all-subtransformer: [8, 8, 8, 8, 8, 8]
decoder-ende-attention-heads-all-subtransformer: [8, 8, 8, 8, 8, 8]

# for arbitrary encoder decoder attention. -1 means attending to last one encoder layer
# 1 means last two encoder layers, 2 means last three encoder layers
decoder-arbitrary-ende-attn-all-subtransformer: [-1, -1, -1, -1, -1, -1]

encoder-block-types-all-subtransformer: [lightweight_conv, lightweight_conv, lightweight_conv, lightweight_conv, lightweight_conv, lightweight_conv]
decoder-block-types-all-subtransformer: [lightweight_conv, lightweight_conv, lightweight_conv, lightweight_conv, lightweight_conv, lightweight_conv]
