encoder-embed-dim-subtransformer: 512
decoder-embed-dim-subtransformer: 512

encoder-ffn-embed-dim-all-subtransformer: [1024, 1024, 1024, 1024, 1024, 3072]
decoder-ffn-embed-dim-all-subtransformer: [3072, 3072, 3072]

encoder-layer-num-subtransformer: 6
decoder-layer-num-subtransformer: 3

encoder-self-attention-heads-all-subtransformer: [8, 4, 8, 8, 16, 16]
decoder-self-attention-heads-all-subtransformer: [8, 16, 16]
decoder-ende-attention-heads-all-subtransformer: [4, 4, 4]

decoder-arbitrary-ende-attn-all-subtransformer: [-1, 1, 2]

encoder-block-types-all-subtransformer: [self_attention, self_attention+lightweight_shiftadd, self_attention+lightweight_conv, self_attention+lightweight_shiftadd, self_attention, self_attention]
decoder-block-types-all-subtransformer: [self_attention+lightweight_conv, self_attention, self_attention, self_attention+lightweight_shiftadd, self_attention, self_attention+lightweight_shiftadd]
