encoder-embed-dim-subtransformer: 512
decoder-embed-dim-subtransformer: 512

encoder-ffn-embed-dim-all-subtransformer: [2048, 3072, 2048, 3072, 1024, 4096]
decoder-ffn-embed-dim-all-subtransformer: [3072, 3072, 3072, 3072]

encoder-layer-num-subtransformer: 6
decoder-layer-num-subtransformer: 4

encoder-self-attention-heads-all-subtransformer: [8, 16, 8, 8, 16, 8]
decoder-self-attention-heads-all-subtransformer: [8, 16, 16, 4]
decoder-ende-attention-heads-all-subtransformer: [4, 4, 4, 8]

decoder-arbitrary-ende-attn-all-subtransformer: [-1, 2, 2, 2]

encoder-block-types-all-subtransformer: [self_attention+lightweight_conv, self_attention+lightweight_shiftadd, self_attention+lightweight_conv, self_attention+lightweight_shiftadd, self_attention, self_attention]
decoder-block-types-all-subtransformer: [self_attention+lightweight_conv, self_attention, self_attention, self_attention, self_attention+lightweight_conv, self_attention+lightweight_shiftadd]
