# model
arch: transformersuper_shiftadd_v2_iwslt_de_en_big
max-tokens: 4096
data: data/binary/iwslt14_de_en
source-lang: de
target-lang: en

# training settings
distributed-world-size: 1
optimizer: adam
adam-betas: (0.9, 0.98)
weight-decay: 0.0001
dropout: 0.375
criterion: label_smoothed_cross_entropy
label-smoothing: 0.1

fp16: False

# warmup from warmup-init-lr to lr (warmup-updates steps); then inverse sqrt anneal (max-update - warmup-updates steps)
max-update: 50000
warmup-updates: 10000
lr-scheduler: inverse_sqrt
warmup-init-lr: 1e-7
lr: 0.0005

# logging
keep-last-epochs: 3
save-interval: 1
validate-interval: 5

# SuperTransformer configs
encoder-embed-dim: 1024
decoder-embed-dim: 1024

encoder-ffn-embed-dim: 4096
decoder-ffn-embed-dim: 3072

encoder-layers: 6
decoder-layers: 6

encoder-attention-heads: 16
decoder-attention-heads: 16

qkv-dim: 512

act_path: 1

# SubTransformers search space
encoder-embed-choice: [1024, 768, 640, 512]
decoder-embed-choice: [1024, 768, 640, 512]

encoder-ffn-embed-dim-choice: [4096, 3072, 2048, 1024]
decoder-ffn-embed-dim-choice: [3072, 2048, 1024]

encoder-layer-num-choice: [6]
decoder-layer-num-choice: [6, 5, 4, 3, 2, 1]

encoder-self-attention-heads-choice: [16, 8, 4, 2]
decoder-self-attention-heads-choice: [16, 8, 4, 2]
decoder-ende-attention-heads-choice: [16, 8, 4, 2]

encoder-block-types: [lightweight_conv, lightweight_add, lightweight_shiftadd, self_attention, self_attention+lightweight_conv, self_attention+lightweight_add, self_attention+lightweight_shiftadd]
decoder-block-types: [self_attention, self_attention+lightweight_conv, self_attention+lightweight_add, self_attention+lightweight_shiftadd]

# for arbitrary encoder decoder attention. -1 means attending to last one encoder layer
# 1 means last two encoder layers, 2 means last three encoder layers
decoder-arbitrary-ende-attn-choice: [-1, 1, 2]

# new added
encoder-glu: 1
decoder-glu: 1
weight-dropout: 0.03
encoder-branch-type: [attn:1:1024:4, lightweight:default:1024:4]
decoder-branch-type: [attn:1:1024:4, lightweight:default:1024:4]
conv-linear: true
save-interval: 1
validate-interval: 10